In [1]:
!pip install numpy
!pip install qubovert
!pip install matplotlib
!pip install pickle
!pip install pyyaml
!pip install pandas

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [2]:
import pickle
import numpy as np
import qubovert

In [3]:
teachers = 5
lectures = 2
weeks = 2
days = 6
hours = 8
groups = 2

main_vars = teachers * lectures * weeks * days * hours * groups
cons_1 = teachers * weeks * days * hours
cons_2 = weeks * days * hours * groups
cons_3 = weeks * days * groups * 3
cons_4 = teachers * lectures * weeks * days * groups * 2

p = 50
BB = 10
B = 20
QUBO_size = main_vars + cons_1 + cons_2 + cons_3 + cons_4
QUBO = np.zeros((QUBO_size, QUBO_size))
QUBO.shape

(3144, 3144)

## Constraint 1

In [4]:
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups
                        
                        x = lecture * weeks * days * hours * groups + group
                        for l1 in range(lectures):
                            for g1 in range(groups):
                                y = l1 * weeks * days * hours * groups + g1
                                QUBO[index + x][index + y] += 1 * p

for teacher in range(teachers):
    for week in range(weeks):
        for day in range(days):
            for hour in range(hours):
                index = teacher * weeks * days * hours + \
                        week * days * hours + \
                        day * hours + \
                        hour
                QUBO[main_vars + index][main_vars + index] += 1 * p
                
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        y = teacher * weeks * days * hours + \
                            week * days * hours + \
                            day * hours + \
                            hour
                        
                        QUBO[index][main_vars + y] += 1 * p
                        QUBO[main_vars + y][index] += 1 * p
                        
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days * hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        QUBO[index][index] -= 2 * p

for teacher in range(teachers):
    for week in range(weeks):
        for day in range(days):
            for hour in range(hours):
                index = teacher * weeks * days * hours + \
                        week * days * hours + \
                        day * hours + \
                        hour
                QUBO[main_vars + index][main_vars + index] -= 2 * p

## Constraint 2

In [5]:
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        x = teacher * lectures * weeks * days * hours * groups + \
                            lecture * weeks * days * hours * groups
                        for t1 in range(teachers):
                            for l1 in range(lectures):
                                y = t1 * lectures * weeks * days * hours * groups + \
                                    l1 * weeks * days * hours * groups
                                QUBO[index + x][index + y] += 1 * p

for week in range(weeks):
    for day in range(days):
        for hour in range(hours):
            for group in range(groups):
                index = week * days * hours * groups + \
                        day * hours * groups + \
                        hour * groups + \
                        group
                QUBO[main_vars + cons_1 + index][main_vars + cons_1 + index] += 1 * p
                
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        y = week * days * hours * groups + \
                            day * hours * groups + \
                            hour * groups + \
                            group
                        
                        QUBO[index][main_vars + cons_1 + y] += 1 * p
                        QUBO[main_vars + cons_1 + y][index] += 1 * p
                        
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        QUBO[index][index] -= 2 * p

for week in range(weeks):
    for day in range(days):
        for hour in range(hours):
            for group in range(groups):
                index = week * days * hours * groups + \
                        day * hours * groups + \
                        hour * groups + \
                        group
                QUBO[main_vars + cons_1 + index][main_vars + cons_1 + index] -= 2 * p

## Constraint 3

In [6]:
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = week * days * hours * groups + \
                                day * hours * groups + \
                                group
                        
                        x = teacher * lectures * weeks * days * hours * groups + \
                            lecture * weeks * days * hours * groups + \
                            hour * groups
                        for t1 in range(teachers):
                            for l1 in range(lectures):
                                for h1 in range(hours):
                                    y = t1 * lectures * weeks * days * hours * groups + \
                                        l1 * weeks * days * hours * groups + \
                                        h1 * groups
                                    QUBO[index + x][index + y] += 1

for week in range(teachers):
    for lecture in range(lectures):
        for group in range(groups):
            index = week * days * groups + \
                    day * groups + \
                    group
            
            for bit1 in range(3):
                for bit2 in range(3):
                    y = main_vars + cons_1 + cons_2 + index
                    QUBO[y + bit2][y + bit1] += (1 << bit1) * (1 << bit2)
                    
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        for bit in range(3):
                            y = main_vars + cons_1 + cons_2 + \
                                week * days * groups + \
                                day * groups + \
                                group + \
                                bit
                            QUBO[index][y] += (1 << bit)
                            QUBO[y][index] += (1 << bit)
                            
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        QUBO[index][index] -= (12)

for week in range(teachers):
    for lecture in range(lectures):
        for group in range(groups):
            for bit in range(3):
                y = main_vars + cons_1 + cons_2 + \
                    week * days * groups + \
                    day * groups + \
                    group + \
                    bit
                QUBO[y][y] -= (6 * (1 << bit))

## Constraint 4

In [7]:
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days * hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                group
                        
                        x = hour * groups
                        for h1 in range(hours):
                            y = h1 * groups
                            QUBO[index + x][index + y] += (1 * p)
                            
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for group in range(groups):
                    index = teacher * lectures * weeks * days * groups + \
                            lecture * weeks * days * groups + \
                            week * days * groups + \
                            day * groups + \
                            group
                    for bit1 in range(2):
                        for bit2 in range(2):
                            y = main_vars + cons_1 + cons_2 + cons_3 + index
                            QUBO[y + bit2][y + bit1] += (1 << bit1) * (1 << bit2)
                            
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        for bit in range(2):
                            y = main_vars + cons_1 + cons_2 + cons_3 + \
                                teacher * lectures * weeks * days * groups + \
                                lecture * weeks * days * groups + \
                                week * days * groups + \
                                day * groups + \
                                group + \
                                bit
                            QUBO[index][y] += (1 << bit) * p
                            QUBO[y][index] += (1 << bit) * p
                            
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        QUBO[index][index] -= (4 * p)
                        
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for group in range(groups):
                    for bit in range(2):
                        y = main_vars + cons_1 + cons_2 + cons_3 + \
                            teacher * lectures * weeks * days * groups + \
                            lecture * weeks * days * groups + \
                            week * days * groups + \
                            day * groups + \
                            group + \
                            bit
                        QUBO[y][y] -= (4 * (1 << bit) * p)

## Constraint 5

In [8]:
weekends = [(0,2), (1,0), (2,5), (3,1), (4,1)]
for weekend in weekends:
    for lecture in range(lectures):
        for week in range(weeks):
            for hour in range(hours):
                for group in range(groups):
                    index = weekend[0] * lectures * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                weekend[1] * hours * groups
                        
                    x = lecture * weeks * days * hours * groups + \
                            hour * groups + \
                            group
                        
                    for l1 in range(lectures):
                        for h1 in range(hours):
                            for g1 in range(groups):
                                y = l1 * weeks * days * hours * groups + \
                                        h1 * groups + \
                                        g1
                                QUBO[index + x][index + y] += (1 * p)

## Constraint 6

In [9]:
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days * hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                group
                        
                        x = week * days * hours * groups + \
                            day * hours * groups + \
                            hour * groups
                        
                        for w1 in range(weeks):
                            for d1 in range(days):
                                for h1 in range(hours):
                                    y = w1 * days * hours * groups + \
                                        d1 * hours * groups + \
                                        h1 * groups
                                    QUBO[index + x][index + y] += (1 * p)
                                    
for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        
                        QUBO[index][index] -= (8 * p)

In [10]:
pickle.dump(QUBO, open("QUBO_1.pkl","wb"))

In [11]:
import yaml
with open('solution11.yaml', 'r') as f:
    sol = yaml.safe_load(f)

In [12]:
solution = np.zeros(1920)
len(sol)
count = 0
for i in range(1920):
    solution[i] = sol[0]['solution']['variables']['b_'+str(i)]
    if (solution[i] == 1):
        count += 1
print(count)

80


In [13]:
import pandas as pd
dict_teachers = {'Name':['Иванов', 'Петров', 'Сидоров', 'Карпов','Соколов']}
dict_groups = {'Group':['QC_1', 'QC_2']}
dict_weeks = {'Week':['неделя 1', 'неделя 2']}
dict_days = {'Day':['пн','вт','ср','чт','пт','сб']}
dict_hours = {'Hour':['9:00-10:00', '10:00-11:00', '11:00-12:00', '12:00-13:00', '13:00-14:00', '14:00-15:00', '15:00-16:00', '16:00-17:00']}
dict_subjects = {'Subject':['Квантовая механика',
                            'Квантовая теория информации',
                            'Квантовые вычисления',
                            'Сложность квантовых алгоритмов',
                            'Квантовые алгоритмы в логистике',
                            'Квантовое машинное обучение',
                            'Моделирование квантовых систем',
                            'Квантовые алгоритмы в химии',
                            'Физическая реализация квантовых компьютеров',
                            'Моделирование квантовых алгоритмов']}

In [14]:
table = []

for teacher in range(teachers):
    for lecture in range(lectures):
        for week in range(weeks):
            for day in range(days):
                for hour in range(hours):
                    for group in range(groups):
                        index = teacher * lectures * weeks * days* hours * groups + \
                                lecture * weeks * days * hours * groups + \
                                week * days * hours * groups + \
                                day * hours * groups + \
                                hour * groups + \
                                group
                        if (solution[index] == 1):
                            table.append([group, week, day, hour, lecture, teacher])

In [15]:
print(np.array(table))

[[0 0 0 3 0 0]
 [0 0 1 1 0 0]
 [1 0 5 6 0 0]
 [0 1 0 7 0 0]
 [0 1 1 3 0 0]
 [1 1 1 4 0 0]
 [1 1 4 4 0 0]
 [1 1 5 4 0 0]
 [0 0 1 6 1 0]
 [0 0 4 4 1 0]
 [1 0 4 4 1 0]
 [1 0 5 2 1 0]
 [0 0 5 7 1 0]
 [1 1 0 0 1 0]
 [0 1 1 7 1 0]
 [1 1 4 1 1 0]
 [1 0 1 4 0 1]
 [1 0 2 6 0 1]
 [0 0 3 3 0 1]
 [0 0 5 0 0 1]
 [1 0 5 3 0 1]
 [1 1 1 0 0 1]
 [0 1 2 1 0 1]
 [0 1 5 1 0 1]
 [1 0 1 0 1 1]
 [0 0 1 6 1 1]
 [0 0 2 7 1 1]
 [1 0 3 0 1 1]
 [0 0 3 6 1 1]
 [1 0 4 7 1 1]
 [0 1 3 0 1 1]
 [1 1 3 2 1 1]
 [0 0 0 0 0 2]
 [1 0 0 1 0 2]
 [1 0 1 0 0 2]
 [1 0 2 0 0 2]
 [0 0 4 2 0 2]
 [0 1 0 1 0 2]
 [1 1 1 1 0 2]
 [0 1 4 4 0 2]
 [0 0 0 2 1 2]
 [0 0 2 5 1 2]
 [1 0 3 0 1 2]
 [0 0 4 0 1 2]
 [0 1 1 7 1 2]
 [1 1 2 2 1 2]
 [1 1 3 1 1 2]
 [1 1 4 6 1 2]
 [1 0 0 1 0 3]
 [1 0 2 7 0 3]
 [0 0 3 2 0 3]
 [1 0 4 4 0 3]
 [0 0 5 0 0 3]
 [0 1 0 4 0 3]
 [0 1 4 5 0 3]
 [1 1 5 3 0 3]
 [1 0 2 1 1 3]
 [1 0 3 5 1 3]
 [1 1 0 5 1 3]
 [0 1 0 7 1 3]
 [1 1 3 0 1 3]
 [0 1 3 2 1 3]
 [0 1 4 2 1 3]
 [0 1 5 4 1 3]
 [1 0 0 2 0 4]
 [0 0 2 6 0 4]
 [1 1 0 0 

In [16]:
wdh = []
for g in range(2):
    for i in range(2):
        for j in range(6):
            for k in range(8):
                wdh.append([g,i, j, k,'нет занятий','нет занятий'])

In [17]:
df = pd.DataFrame(wdh, columns = ['Group','Week', 'Day', 'Hour','Subject','Name'])

In [18]:
df

Group  Week  Day  Hour      Subject         Name
0        0     0    0     0  нет занятий  нет занятий
1        0     0    0     1  нет занятий  нет занятий
2        0     0    0     2  нет занятий  нет занятий
3        0     0    0     3  нет занятий  нет занятий
4        0     0    0     4  нет занятий  нет занятий
..     ...   ...  ...   ...          ...          ...
187      1     1    5     3  нет занятий  нет занятий
188      1     1    5     4  нет занятий  нет занятий
189      1     1    5     5  нет занятий  нет занятий
190      1     1    5     6  нет занятий  нет занятий
191      1     1    5     7  нет занятий  нет занятий

[192 rows x 6 columns]

In [19]:
count = 0

for g in range(2):
    for i in range(2):
        for j in range(6):
            for k in range(8):
                for t in table:
                    if (t[0] == g) and (t[1] == i) and (t[2] == j) and (t[3] == k):
                        df.iat[g * 96 + i * 48 + j * 8 + k,0] = dict_groups['Group'][g]
                        df.iat[g * 96 + i * 48 + j * 8 + k,1] = dict_weeks['Week'][i]
                        df.iat[g * 96 + i * 48 + j * 8 + k,2] = dict_days['Day'][j]
                        df.iat[g * 96 + i * 48 + j * 8 + k,3] = dict_hours['Hour'][k]
                        df.iat[g * 96 + i * 48 + j * 8 + k,5] = dict_teachers['Name'][t[5]]
                        df.iat[g * 96 + i * 48 + j * 8 + k,4] = dict_subjects['Subject'][t[5] * 2 + t[4]]
                        print(df.iloc[[g * 96 + i * 48 + j * 8 + k]])
                        count+=1
                        

for g in range(2):
    for i in range(2):
        for j in range(6):
             for k in range(8):
                if (df.iat[g * 96 + i * 48 + j * 8 + k,4] == "нет занятий"):
                    df.iat[g * 96 + i * 48 + j * 8 + k,0] = dict_groups['Group'][g]
                    df.iat[g * 96 + i * 48 + j * 8 + k,1] = dict_weeks['Week'][i]
                    df.iat[g * 96 + i * 48 + j * 8 + k,2] = dict_days['Day'][j]
                    df.iat[g * 96 + i * 48 + j * 8 + k,3] = dict_hours['Hour'][k]
df

  Group      Week Day        Hour                          Subject     Name
0  QC_1  неделя 1  пн  9:00-10:00  Квантовые алгоритмы в логистике  Сидоров
  Group      Week Day         Hour                      Subject     Name
2  QC_1  неделя 1  пн  11:00-12:00  Квантовое машинное обучение  Сидоров
  Group      Week Day         Hour             Subject    Name
3  QC_1  неделя 1  пн  12:00-13:00  Квантовая механика  Иванов
  Group      Week Day         Hour             Subject    Name
9  QC_1  неделя 1  вт  10:00-11:00  Квантовая механика  Иванов
   Group      Week Day         Hour                      Subject    Name
14  QC_1  неделя 1  вт  15:00-16:00  Квантовая теория информации  Иванов
   Group      Week Day         Hour                         Subject    Name
14  QC_1  неделя 1  вт  15:00-16:00  Сложность квантовых алгоритмов  Петров
   Group      Week Day         Hour                             Subject  \
19  QC_1  неделя 1  ср  12:00-13:00  Моделирование квантовых алгоритмов   

 

Group      Week Day         Hour                          Subject  \
0    QC_1  неделя 1  пн   9:00-10:00  Квантовые алгоритмы в логистике   
1    QC_1  неделя 1  пн  10:00-11:00                      нет занятий   
2    QC_1  неделя 1  пн  11:00-12:00      Квантовое машинное обучение   
3    QC_1  неделя 1  пн  12:00-13:00               Квантовая механика   
4    QC_1  неделя 1  пн  13:00-14:00                      нет занятий   
..    ...       ...  ..          ...                              ...   
187  QC_2  неделя 2  сб  12:00-13:00   Моделирование квантовых систем   
188  QC_2  неделя 2  сб  13:00-14:00               Квантовая механика   
189  QC_2  неделя 2  сб  14:00-15:00                      нет занятий   
190  QC_2  неделя 2  сб  15:00-16:00                      нет занятий   
191  QC_2  неделя 2  сб  16:00-17:00                      нет занятий   

            Name  
0        Сидоров  
1    нет занятий  
2        Сидоров  
3         Иванов  
4    нет занятий  
..           ...  
187       Карпов  
188       Иванов  
189  нет занятий  
190  нет занятий  
191  нет занятий  

[192 rows x 6 columns]

In [20]:
print(count)

80


In [21]:
df.to_csv("solution.csv")

In [23]:
custom_dict_group = {'QC_1': 0, 'QC_2': 1}
custom_dict_week = {'неделя 1': 0, 'неделя 2': 1}
custom_dict_day = {'пн': 0, 'вт': 1, 'ср': 2, 'чт': 3, 'пт': 4, 'сб': 5, 'вс': 6}
custom_dict_hour = {'9:00-10:00': 0, '10:00-11:00': 1, '11:00-12:00': 2, '12:00-13:00': 3, '13:00-14:00': 4, '14:00-15:00': 5, '15:00-16:00': 6, '16:00-17:00': 7}


pll = df.sort_values(by=['Day'], key=lambda x: x.map(custom_dict_day) , ignore_index=True)

In [24]:
pll['Group_N'] =  pll['Group'].apply(lambda x: custom_dict_group[x])
pll['Week_N'] =  pll['Week'].apply(lambda x: custom_dict_week[x])
pll['Day_N'] =  pll['Day'].apply(lambda x: custom_dict_day[x])
pll['Hour_N'] =  pll['Hour'].apply(lambda x: custom_dict_hour[x])

In [25]:
pll

Group      Week Day         Hour                             Subject  \
0    QC_1  неделя 1  пн   9:00-10:00     Квантовые алгоритмы в логистике   
1    QC_2  неделя 2  пн  14:00-15:00  Моделирование квантовых алгоритмов   
2    QC_2  неделя 2  пн  12:00-13:00                         нет занятий   
3    QC_2  неделя 2  пн  11:00-12:00                         нет занятий   
4    QC_2  неделя 2  пн  10:00-11:00                         нет занятий   
..    ...       ...  ..          ...                                 ...   
187  QC_2  неделя 1  сб  12:00-13:00                Квантовые вычисления   
188  QC_2  неделя 1  сб  13:00-14:00                         нет занятий   
189  QC_2  неделя 1  сб  14:00-15:00                         нет занятий   
190  QC_1  неделя 2  сб  12:00-13:00                         нет занятий   
191  QC_2  неделя 2  сб  16:00-17:00                         нет занятий   

            Name  Group_N  Week_N  Day_N  Hour_N  
0        Сидоров        0       0      0       0  
1        Соколов        1       1      0       5  
2    нет занятий        1       1      0       3  
3    нет занятий        1       1      0       2  
4    нет занятий        1       1      0       1  
..           ...      ...     ...    ...     ...  
187       Петров        1       0      5       3  
188  нет занятий        1       0      5       4  
189  нет занятий        1       0      5       5  
190  нет занятий        0       1      5       3  
191  нет занятий        1       1      5       7  

[192 rows x 10 columns]

In [26]:
pll = pll.sort_values(by=['Group_N','Week_N','Day_N','Hour_N'], ignore_index=True)

In [27]:
pl = pll

In [28]:
pld=pl.drop(['Group_N','Week_N','Day_N','Hour_N'], axis =1)

In [29]:
pld.to_csv("./solution_sort.csv", index=False)

In [30]:
custom_dict_subject = {'Квантовая механика': 0, 'Квантовая теория информации': 1, 'Квантовые вычисления': 2, 'Сложность квантовых алгоритмов': 3, 'Квантовые алгоритмы в логистике': 4,
                        'Квантовое машинное обучение': 5, 'Моделирование квантовых систем': 6, 'Квантовые алгоритмы в химии': 7,'Физическая реализация квантовых компьютеров': 8,
                        'Моделирование квантовых алгоритмов': 9, 'нет занятий': 10}
custom_dict_subjectyn = {'Квантовая механика': 1, 'Квантовая теория информации': 1, 'Квантовые вычисления': 1, 'Сложность квантовых алгоритмов': 1, 'Квантовые алгоритмы в логистике': 1,
                        'Квантовое машинное обучение': 1, 'Моделирование квантовых систем': 1, 'Квантовые алгоритмы в химии': 1,'Физическая реализация квантовых компьютеров': 1,
                        'Моделирование квантовых алгоритмов': 1, 'нет занятий': 0}

custom_dict_teacher = {'Иванов': 0, 'Петров': 1, 'Сидоров': 2, 'Карпов': 3, 'Соколов': 4, 'нет занятий': 10}
custom_dict_teacheryn = {'Иванов': 1, 'Петров': 1, 'Сидоров': 1, 'Карпов': 1, 'Соколов': 1, 'нет занятий': 0}


pll['Subject_N'] =  pll['Subject'].apply(lambda x: custom_dict_subject[x])
pll['Subject_yn'] =  pll['Subject'].apply(lambda x: custom_dict_subjectyn[x])
pll['Teacher_N'] =  pll['Name'].apply(lambda x: custom_dict_teacher[x])
pll['Teacher_yn'] =  pll['Name'].apply(lambda x: custom_dict_teacheryn [x])


pll['Day_N_thru'] = pll['Week_N']*6 + pll['Day_N']

pll['Hour_N_thru'] = pll['Group_N']*2*6*8 + pll['Week_N']*6*8 + pll['Day_N']*8 + pll['Hour_N']

pll

Group      Week Day         Hour                          Subject  \
0    QC_1  неделя 1  пн   9:00-10:00  Квантовые алгоритмы в логистике   
1    QC_1  неделя 1  пн  10:00-11:00                      нет занятий   
2    QC_1  неделя 1  пн  11:00-12:00      Квантовое машинное обучение   
3    QC_1  неделя 1  пн  12:00-13:00               Квантовая механика   
4    QC_1  неделя 1  пн  13:00-14:00                      нет занятий   
..    ...       ...  ..          ...                              ...   
187  QC_2  неделя 2  сб  12:00-13:00   Моделирование квантовых систем   
188  QC_2  неделя 2  сб  13:00-14:00               Квантовая механика   
189  QC_2  неделя 2  сб  14:00-15:00                      нет занятий   
190  QC_2  неделя 2  сб  15:00-16:00                      нет занятий   
191  QC_2  неделя 2  сб  16:00-17:00                      нет занятий   

            Name  Group_N  Week_N  Day_N  Hour_N  Subject_N  Subject_yn  \
0        Сидоров        0       0      0       0          4           1   
1    нет занятий        0       0      0       1         10           0   
2        Сидоров        0       0      0       2          5           1   
3         Иванов        0       0      0       3          0           1   
4    нет занятий        0       0      0       4         10           0   
..           ...      ...     ...    ...     ...        ...         ...   
187       Карпов        1       1      5       3          6           1   
188       Иванов        1       1      5       4          0           1   
189  нет занятий        1       1      5       5         10           0   
190  нет занятий        1       1      5       6         10           0   
191  нет занятий        1       1      5       7         10           0   

     Teacher_N  Teacher_yn  Day_N_thru  Hour_N_thru  
0            2           1           0            0  
1           10           0           0            1  
2            2           1           0            2  
3            0           1           0            3  
4           10           0           0            4  
..         ...         ...         ...          ...  
187          3           1          11          187  
188          0           1          11          188  
189         10           0          11          189  
190         10           0          11          190  
191         10           0          11          191  

[192 rows x 16 columns]

In [31]:
#0.1.1 У двух групп занятия не могут идти одновременно с одним преподавателем
import numpy as np

def prove_011():
    pl1 = pll[(pll.Group =='QC_1')].reset_index(drop=True)
    pl2 = pll[(pll.Group =='QC_2')].reset_index(drop=True)
    plcompare = pl1

    plcompare['equal'] = ((pl1['Subject'] == pl2['Subject']) & (pl1['Subject'] != 'нет занятий'))

    return bool(not (plcompare['equal']=='False').sum())

prove_011()

True

In [32]:
#0.2 Преподаватель не может одновременно вести два предмета

def prove_02():
    pl1 = pl[(pl.Group =='QC_1') ].reset_index(drop=True)
    pl2 = pl[(pl.Group =='QC_2') ].reset_index(drop=True)
    plcompare = pl1
    plcompare['equal'] = (pl1['Name'] == pl2['Name']) & (pl2['Name'] != 'нет занятий')

    return bool(not (plcompare['equal']=='False').sum())

prove_02()

True

In [33]:
#0.3 У группы может идти только одно занятие в срезе группа-день-час

def prove_03():
    pl1 = pl[(pl.Group =='QC_1') & pl.Subject != 'нет занятий'].reset_index(drop=True)
    pl2 = pl[(pl.Group =='QC_2') & pl.Subject != 'нет занятий'].reset_index(drop=True)
    s1 =len(pl1['Hour_N_thru'])- len(pl1['Hour_N_thru'].drop_duplicates())
    s2= len(pl2['Hour_N_thru'])- len(pl2['Hour_N_thru'].drop_duplicates())

    return bool(not (s1+s2)),s1,s2

prove_03()



(True, 0, 0)

In [34]:
#2. В день может быть поставлено не более 6 лекций в расписании группы

def prove_02():
    pl1 = pl[(pl.Group =='QC_1') ].reset_index(drop=True)
    pl2 = pl[(pl.Group =='QC_2') ].reset_index(drop=True)

    #lessons_per_day_gr1 = []
    #for i in range(len(pl1)):
    s1 =pl1.groupby(['Day_N_thru'])['Subject_yn'].sum()
    s2 =pl2.groupby(['Day_N_thru'])['Subject_yn'].sum()

    return bool((s1.max()<=6) & (s2.max() <=6)), s1,s2

prove_02()

(True,
 Day_N_thru
 0     3
 1     2
 2     4
 3     3
 4     3
 5     2
 6     3
 7     2
 8     3
 9     2
 10    3
 11    3
 Name: Subject_yn, dtype: int64,
 Day_N_thru
 0     3
 1     2
 2     4
 3     3
 4     2
 5     3
 6     2
 7     3
 8     3
 9     3
 10    3
 11    3
 Name: Subject_yn, dtype: int64)

In [35]:
#3. В день не может быть более двух занятий по одному предмету у группы.

def prove_03():
    pl1 = pl[(pl.Group =='QC_1') ].reset_index(drop=True)
    pl2 = pl[(pl.Group =='QC_2') ].reset_index(drop=True)

    #lessons_per_day_gr1 = []
    #for i in range(len(pl1)):
    s1 =pl1.groupby(['Day_N_thru', 'Subject'])['Subject_yn'].sum()
    s2 =pl2.groupby(['Day_N_thru', 'Subject'])['Subject_yn'].sum()

    return bool((s1.max()<=2) & (s2.max() <=2)), s1,s2

prove_03()

(True,
 Day_N_thru  Subject                                    
 0           Квантовая механика                             1
             Квантовое машинное обучение                    1
             Квантовые алгоритмы в логистике                1
             нет занятий                                    0
 1           Квантовая механика                             1
             Сложность квантовых алгоритмов                 1
             нет занятий                                    0
 2           Квантовое машинное обучение                    1
             Моделирование квантовых алгоритмов             1
             Сложность квантовых алгоритмов                 1
             Физическая реализация квантовых компьютеров    1
             нет занятий                                    0
 3           Квантовые вычисления                           1
             Моделирование квантовых систем                 1
             Сложность квантовых алгоритмов                 1
      

In [36]:
#4 Так получилось, что преподаватель n1 не может вести лекции в среду,
#а n2 в понедельник, а n3 никак не может работать по субботам, n4, n5 –
#не могут вести занятия по вторникам. Воскресенье - день без занятий

def prove_04():

  n1 = pl[(pl['Name']=='Иванов') & (pl['Day']=='cр')].groupby(['Subject'])['Subject_yn'].count()
  n2 = pl[(pl['Name']=='Петров') &(pl['Day']=='пн')].groupby(['Subject'])['Subject_yn'].count()
  n3 = pl[(pl['Name']=='Сидоров') &(pl['Day']=='сб')].groupby(['Subject'])['Subject_yn'].count()
  n4 = pl[(pl['Name']=='Карпов') &(pl['Day']=='вт')].groupby(['Subject'])['Subject_yn'].count()
  n5 = pl[(pl['Name']=='Соколов') &(pl['Day']=='вт')].groupby(['Subject'])['Subject_yn'].count()


  return  bool((len(n1)== 0) & (len(n2)== 0) & (len(n3)== 0) & (len(n4)== 0) & (len(n5)== 0)), len(n1),len(n2),len(n3),len(n4),len(n5)

prove_04()

(True, 0, 0, 0, 0, 0)

In [37]:
# 5.По требованию учебной программы для каждого предмета должно быть выделено
# 4 часа за период T = 2 недели для каждой группы.

def prove_05():

    s1 =pl[(pl.Group =='QC_1') & (pl.Subject != 'нет занятий')].groupby(['Subject'])['Subject_yn'].sum()
    s2 =pl[(pl.Group =='QC_2') & (pl.Subject != 'нет занятий')].groupby(['Subject'])['Subject_yn'].sum()

    return bool((s2.min() == 4) & (s2.max() == 4) & (s2.min() == 4) & (s2.max() == 4)), s1, s2

prove_05()


(False,
 Subject
 Квантовая механика                             3
 Квантовая теория информации                    2
 Квантовое машинное обучение                    4
 Квантовые алгоритмы в логистике                4
 Квантовые алгоритмы в химии                    1
 Квантовые вычисления                           3
 Моделирование квантовых алгоритмов             4
 Моделирование квантовых систем                 4
 Сложность квантовых алгоритмов                 4
 Физическая реализация квантовых компьютеров    4
 Name: Subject_yn, dtype: int64,
 Subject
 Квантовая механика                             4
 Квантовая теория информации                    2
 Квантовое машинное обучение                    4
 Квантовые алгоритмы в логистике                3
 Квантовые алгоритмы в химии                    3
 Квантовые вычисления                           4
 Моделирование квантовых алгоритмов             4
 Моделирование квантовых систем                 4
 Сложность квантовых алгоритмов          

In [38]:
#6. Каждый преподаватель имеет ограниченное число часов в неделю на
# работу E ≤ 20.

def prove_06():

    n1_1 = pl[(pl['Name']=='Иванов') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()
    n1_2 = pl[(pl['Name']=='Иванов') & (pl['Week']=='неделя 2')].groupby(['Name'])['Subject_yn'].sum()

    n2_1 = pl[(pl['Name']=='Петров') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()
    n2_2 = pl[(pl['Name']=='Петров') & (pl['Week']=='неделя 2')].groupby(['Name'])['Subject_yn'].sum()

    n3_1 = pl[(pl['Name']=='Сидоров') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()
    n3_2 = pl[(pl['Name']=='Сидоров') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()

    n4_1 = pl[(pl['Name']=='Карпов') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()
    n4_2 = pl[(pl['Name']=='Карпов') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()

    n5_1 =pl[(pl['Name']=='Соколов') & (pl['Week']=='неделя 1')].groupby(['Name'])['Subject_yn'].sum()
    n5_2 =pl[(pl['Name']=='Соколов') & (pl['Week']=='неделя 2')].groupby(['Name'])['Subject_yn'].sum()

    return bool((int(n1_1) <=20) & (int(n1_2) <=20) & (int(n2_1) <=20) & (int(n2_2) <=20) & (int(n3_1) <=20) & (int(n3_2) <=20) & (int(n4_1) <=20) & (int(n4_2) <=20) & (int(n5_1) <=20) & (int(n5_2) <=20))

prove_06()


C:\Users\pavel\AppData\Local\Temp\ipykernel_18780\916551412.py:21: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  return bool((int(n1_1) <=20) & (int(n1_2) <=20) & (int(n2_1) <=20) & (int(n2_2) <=20) & (int(n3_1) <=20) & (int(n3_2) <=20) & (int(n4_1) <=20) & (int(n4_2) <=20) & (int(n5_1) <=20) & (int(n5_2) <=20))


True